# Site
repository: mhd-medfa
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Mohamad Al Mdfaa
title: Machine Learning Engineer
email: mohamad.almdfaa@gmail.com
# email_title: Email (Email title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: mohamadalmadfaa
github_username:  mhd-medfa
stackoverflow_username: "4051693"
linkedin_username: mohamad-al-mdfaa
googlescholar_username: GMxT5i4AAAAJ

# # Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# # - title: another link
# #   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
# #   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/personal-photo.jpg
about_content: | # this will include new lines to allow paragraphs
  👨‍💻 Blurring the line between human and machine perception. 🎓 Ph.D. student
   in the <a href="https://sites.skoltech.ru/mobilerobotics/">Mobile Robotics Laboratory</a> at
    Skoltech 🤖 under the supervision of <a href="https://faculty.skoltech.ru/people/gonzaloferrer">Gonzalo Ferrer</a>.
   🔭 Working in the field of Computer Vision 📷 and Visual Localization 🗺️. 🎓 I have a Master's degree in Robotics and
    Computer Vision 🤖👀 at Innopolis University. 💻 With hands-on experience in data science 📊, 
    I possess a strong foundation in machine learning 🤖 and a passion for utilizing it to solve complex
     real-world problems 🌍, with a focus on computer vision 📷.

# Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.

# You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
#   - Lists
#   - Tables
#   - <a href="google.com">Links</a>
#   - Images ![alt text](/images/landscape-trees.jpg "Trees")

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Mobile Robotics Lab, Skoltech University
        sub_title: Deep Learning Research Intern (Part-Time)
        caption: 01/2023 - Present
        quote: >
          Contributing to Visual Localization projects, utilizing techniques such as Visual SLAM, Keypoint Extraction, Image Retrieval, and IMU Integration.
        description: |
          - Involved in Visual Localization projects.
          - Utilized techniques such as Visual SLAM, Keypoint Extraction, Image Retrieval, and IMU Integration.
      - layout: left
        title: BeeOrder
        sub_title: AI Engineer (Full-Time)
        caption: 02/2021 - 01/2022
        quote: >
          Designed and developed an AI system for estimating ETA for delivery from restaurants by the best possible drivers for each client. Developed a system for sorting restaurants based on performance. Maintained Auto Dispatcher System for optimizing delivery routes and finding optimal drivers for each order.
        description: |
          - Designed and developed an AI system for estimating ETA for delivery from restaurants by the best possible drivers for each client.
          - Developed a system for sorting restaurants based on performance.
          - Maintained Auto Dispatcher System for optimizing delivery routes and finding optimal drivers for each order.

      - layout: left
        title: L-One Systems GmbH
        sub_title: Machine Learning Engineer (Full-Time)
        caption: 04/2019 - 08/2020
        quote: >
          Contributed to the Data Science team with expertise in Python, Computer Vision, Machine Learning, and AWS. Developed and implemented machine learning and computer vision systems, including Plant Nutrient Detection (PND) and enhanced Field Boundary Detection systems. Shipped work to production using the AWS ecosystem and was responsible for satellite data processing.
        description: |
          - Contributed to the Data Science team with expertise in Python, Computer Vision, Machine Learning, and AWS.
          - Developed and implemented machine learning and computer vision systems, including Plant Nutrient Detection (PND) and enhanced Field Boundary Detection systems.
          - Shipped work to production using the AWS ecosystem and was responsible for satellite data processing.

      - layout: left
        title: WeStart
        sub_title: AI Engineer (Contract)
        caption: 11/2020 - 01/2022
        quote: >
          Utilized Artificial Intelligence and Deep Learning expertise to support company projects. Worked on RSS-Feed Classification, using BART-based models for summarization and classification, deployed on AWS. Established Reinforcement Learning and A/B testing pipeline for recommender system's profile matching.
        description: |
          - Utilized Artificial Intelligence and Deep Learning expertise to support company projects.
          - Worked on RSS-Feed Classification, using BART-based models for summarization and classification, deployed on AWS.
          - Established Reinforcement Learning and A/B testing pipeline for recommender system's profile matching.

  - title: Technical Projects
    layout: list
    content:
      - layout: left
        border: weak
        title: Vision-based Multi-rotor Aerial Vehicles Tracking for a Moving Object (Master’s Thesis)
        quote: Developed a vision-based tracking system for multi-rotors to follow a moving object in real-time
        description: |
          * Utilized Visual Object Tracking, Deep Learning, and Camera Calibration technologies.
          * Worked with ROS, Python, C++, PyTorch, OpenCV, Docker, Linux, and TensorRT.
          * Published results in a Q1 journal.
        additional_links:
          - title: Github repository
            icon: fab fa-github
            url: https://github.com/mhd-medfa/Single-Object-Tracker
          - title: Article
            icon: fa fa-file-pdf-o
            url: https://www.mdpi.com/1945298
          - title: Webpage
            icon: fa fa-home
            url: https://sites.google.com/view/3d-siammask
      - layout: left
        border: weak
        title: RETA (Restaurant ETA) (BeeOrder)
        quote: Developed a geo-based unsupervised learning approach for estimating delivery time across the company’s outlets.
        description: |
          * Utilized Clustering, Python, Redis, MariaDB, OSRM, Flask, and other technologies
          * Data analysis and machine learning techniques improved the accuracy and efficiency of the delivery time estimation process.
          * Optimized system for real-time performance, contributing to the growth and success of the company.
      - layout: left
        border: weak
        title: Agricultural Nutrient Assistant (ANA) (L-One Systems GmbH)
        quote: Developed a Plant Nutrient Detection tool to analyze images and identify/quantify plant nutrient status
        description: |
          * Maintained Tensorflow 1.13 machine learning models
          * Deployed ANA APIs to production using Flask, Docker, and AWS (EC2, Fargate, Lambda, S3)
          * Achieved cost savings of over 90%.
      - layout: left
        border: weak
        title: Field Boundary API (L-One Systems GmbH)
        description: |
          * Contributed to developing the Field Boundary API, which involved the creation of image processing pipelines to enhance model performance.
          * Utilized a variety of technologies including Python, OpenCV, Numpy, Scipy, Scikit-image, GDAL, rasterio, and AWS Lambda.
      - layout: left
        border: weak
        title: Crowd-Copter Robot (Damascus University)
        quote: Implemented unsupervised learning and computer vision approach for crowd movement analysis.
        description: |
          * Utilized technologies including KNN, Coherent Filter, Quadcopter, Python, Numpy, Pandas, OpenCV, Matplotlib, PyQt, CleanFlight, and Multiwii rewrite PID.

  - title: Education
    layout: list
    content:
      - layout: top-left
        title: Skoltech
        sub_title: Doctor of Philosophy (Ph.D.) - Computer & Data Science & Engineering
        caption: 11/2022 - Present
      - layout: top-left
        title: Innopolis University
        sub_title: Master of Science (MS) in Robotics & Computer Vision
        caption: 09/2020 - 06/2022
        description: |
          Graduated with honor (GPA: 4.83/5) from Innopolis University with a Master of Science degree in Robotics & Computer Vision.

      - layout: top-left
        title: Damascus University
        sub_title: Bachelor of Engineering (B.E.) in Computer & Automation Engineering
        caption: 09/2012 - 09/2017
        description: |
          Completed a Bachelor of Engineering degree in Computer & Automation Engineering from Damascus University with an average score of 77.76%.
  - title: Professional Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      * **Technical Skills:** Deep Learning, Computer Vision, Artificial Intelligence, Machine Learning, Python, PyTorch, Keras,
       Reinforcement Learning, Software System Analysis and Design, Software Project, ROS, OpenCV, Docker,
        Linux, Redis, SQL, Flask, AWS (EC2, Fargate, Lambda, S3), Numpy, Scipy, Scikit-image.
      * **Soft Skills:** Leadership, hardworking, empathy, initiative, teamwork, problem-solving, and communication.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
